## 0. Create Spark session

In [1]:
import os
from pyspark.sql import SparkSession
from pyspark import SparkConf
from pyspark import SparkContext

os.environ['PYSPARK_SUBMIT_ARGS'] = (
    '--packages org.apache.hadoop:hadoop-aws:3.2.0,org.apache.hadoop:hadoop-common:3.2.0 '
    'pyspark-shell'
)
os.environ['S3_ENDPOINT'] = "http://minio:9000"
os.environ['AWS_ACCESS_KEY_ID'] = "minio"
os.environ['AWS_SECRET_ACCESS_KEY'] = "minio123"

if 'spark' in globals():
    spark.stop()
    print("Spark session stopped.")
else:
    print("No Spark session to stop.")

spark = (
    SparkSession.builder.master("spark://spark:7077")
    .appName("notebook-velib-to-siler")
    .config("spark.hadoop.fs.s3a.access.key", os.getenv("AWS_ACCESS_KEY_ID"))
    .config("spark.hadoop.fs.s3a.secret.key", os.getenv("AWS_SECRET_ACCESS_KEY"))
    .config("spark.hadoop.fs.s3a.endpoint", os.getenv("S3_ENDPOINT"))
    .config("spark.hadoop.fs.s3a.connection.ssl.enabled", "false")
    .config("spark.hadoop.fs.s3a.path.style.access", "true")
    .config("spark.hadoop.fs.s3a.attempts.maximum", "1")
    .config("spark.hadoop.fs.s3a.connection.establish.timeout", "5000")
    .config("spark.hadoop.fs.s3a.connection.timeout", "10000")
    .getOrCreate()
)

No Spark session to stop.

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/usr/local/spark-3.1.2-bin-hadoop3.2/jars/spark-unsafe_2.12-3.1.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

:: loading settings :: url = jar:file:/usr/local/spark-3.1.2-bin-hadoop3.2/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml

Ivy Default Cache set to: /home/jovyan/.ivy2/cache
The jars for the packages stored in: /home/jovyan/.ivy2/jars
org.apache.hadoop#hadoop-aws added as a dependency
org.apache.hadoop#hadoop-common added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-08dd3632-27d9-4bd1-b0b7-02d2b0a97b9a;1.0
	confs: [default]
	found org.apache.hadoop#hadoop-aws;3.2.0 in central
	found com.amazonaws#aws-java-sdk-bundle;1.11.375 in central
	found org.apache.hadoop#hadoop-common;3.2.0 in central
	found org.apache.hadoop#hadoop-annotations;3.2.0 in central
	found com.google.guava#guava;11.0.2 in central
	found com.google.code.findbugs#jsr305;3.0.0 in central
	found commons-cli#commons-cli;1.2 in central
	found org.apache.commons#commons-math3;3.1.1 in central
	found org.apache.httpcomponents#httpclient;4.5.2 in central
	found org.apache.httpcomponents#httpcore;4.4.4 in central
	found commons-logging#commons-logging;1.1.3 in central
	found commons-codec#commons-codec;1.11 in central
	found commons-io#commons-io;2.5 in central
	found commons-net#commons-net;3.6 in central
	found commons-collections#commons-collections;3.2.2 in central
	found javax.servlet#javax.servlet-api;3.1.0 in central
	found org.eclipse.jetty#jetty-server;9.3.24.v20180605 in central
	found org.eclipse.jetty#jetty-http;9.3.24.v20180605 in central
	found org.eclipse.jetty#jetty-util;9.3.24.v20180605 in central
	found org.eclipse.jetty#jetty-io;9.3.24.v20180605 in central
	found org.eclipse.jetty#jetty-servlet;9.3.24.v20180605 in central
	found org.eclipse.jetty#jetty-security;9.3.24.v20180605 in central
	found org.eclipse.jetty#jetty-webapp;9.3.24.v20180605 in central
	found org.eclipse.jetty#jetty-xml;9.3.24.v20180605 in central
	found com.sun.jersey#jersey-core;1.19 in central
	found javax.ws.rs#jsr311-api;1.1.1 in central
	found com.sun.jersey#jersey-servlet;1.19 in central
	found com.sun.jersey#jersey-json;1.19 in central
	found org.codehaus.jettison#jettison;1.1 in central
	found com.sun.xml.bind#jaxb-impl;2.2.3-1 in central
	found javax.xml.bind#jaxb-api;2.2.11 in central
	found org.codehaus.jackson#jackson-core-asl;1.9.13 in central
	found org.codehaus.jackson#jackson-mapper-asl;1.9.13 in central
	found org.codehaus.jackson#jackson-jaxrs;1.9.13 in central
	found org.codehaus.jackson#jackson-xc;1.9.13 in central
	found com.sun.jersey#jersey-server;1.19 in central
	found log4j#log4j;1.2.17 in central
	found commons-beanutils#commons-beanutils;1.9.3 in central
	found org.apache.commons#commons-configuration2;2.1.1 in central
	found org.apache.commons#commons-lang3;3.7 in central
	found org.apache.commons#commons-text;1.4 in central
	found org.slf4j#slf4j-api;1.7.25 in central
	found org.slf4j#slf4j-log4j12;1.7.25 in central
	found org.apache.avro#avro;1.7.7 in central
	found com.thoughtworks.paranamer#paranamer;2.3 in central
	found org.xerial.snappy#snappy-java;1.0.5 in central
	found org.apache.commons#commons-compress;1.4.1 in central
	found org.tukaani#xz;1.0 in central
	found com.google.re2j#re2j;1.1 in central
	found com.google.protobuf#protobuf-java;2.5.0 in central
	found com.google.code.gson#gson;2.2.4 in central
	found org.apache.hadoop#hadoop-auth;3.2.0 in central
	found com.nimbusds#nimbus-jose-jwt;4.41.1 in central
	found com.github.stephenc.jcip#jcip-annotations;1.0-1 in central
	found net.minidev#json-smart;2.3 in central
	found net.minidev#accessors-smart;1.2 in central
	found org.ow2.asm#asm;5.0.4 in central
	found org.apache.zookeeper#zookeeper;3.4.13 in central
	found jline#jline;0.9.94 in central
	found org.apache.yetus#audience-annotations;0.5.0 in central
	found io.netty#netty;3.10.5.Final in central
	found org.apache.curator#curator-framework;2.12.0 in central
	found org.apache.curator#curator-client;2.12.0 in central
	found org.apache.kerby#kerb-simplekdc;1.0.1 in central
	found org.apache.kerby#kerb-client;1.0.1 in central
	found org.apache.kerby#kerby-config;1.0.1 in central
	found org.apache.kerby#kerb-core;1.0.1 in central
	found org.apache.kerby#kerby-pkix;1.0.1 in central
	found org.apache.kerby#kerby-asn1;1.0.1 in central
	found org.apache.kerby#kerby-util;1.0.1 in central
	found org.apache.kerby#kerb-common;1.0.1 in central
	found org.apache.kerby#kerb-crypto;1.0.1 in central
	found org.apache.kerby#kerb-util;1.0.1 in central
	found org.apache.kerby#token-provider;1.0.1 in central
	found org.apache.kerby#kerb-admin;1.0.1 in central
	found org.apache.kerby#kerb-server;1.0.1 in central
	found org.apache.kerby#kerb-identity;1.0.1 in central
	found org.apache.kerby#kerby-xdr;1.0.1 in central
	found com.jcraft#jsch;0.1.54 in central
	found org.apache.curator#curator-recipes;2.12.0 in central
	found org.apache.htrace#htrace-core4;4.1.0-incubating in central
	found com.fasterxml.jackson.core#jackson-databind;2.9.5 in central
	found com.fasterxml.jackson.core#jackson-annotations;2.9.5 in central
	found com.fasterxml.jackson.core#jackson-core;2.9.5 in central
	found org.codehaus.woodstox#stax2-api;3.1.4 in central
	found com.fasterxml.woodstox#woodstox-core;5.0.3 in central
	found dnsjava#dnsjava;2.1.7 in central
	found javax.servlet.jsp#jsp-api;2.1 in central
:: resolution report :: resolve 1875ms :: artifacts dl 86ms
	:: modules in use:
	com.amazonaws#aws-java-sdk-bundle;1.11.375 from central in [default]
	com.fasterxml.jackson.core#jackson-annotations;2.9.5 from central in [default]
	com.fasterxml.jackson.core#jackson-core;2.9.5 from central in [default]
	com.fasterxml.jackson.core#jackson-databind;2.9.5 from central in [default]
	com.fasterxml.woodstox#woodstox-core;5.0.3 from central in [default]
	com.github.stephenc.jcip#jcip-annotations;1.0-1 from central in [default]
	com.google.code.findbugs#jsr305;3.0.0 from central in [default]
	com.google.code.gson#gson;2.2.4 from central in [default]
	com.google.guava#guava;11.0.2 from central in [default]
	com.google.protobuf#protobuf-java;2.5.0 from central in [default]
	com.google.re2j#re2j;1.1 from central in [default]
	com.jcraft#jsch;0.1.54 from central in [default]
	com.nimbusds#nimbus-jose-jwt;4.41.1 from central in [default]
	com.sun.jersey#jersey-core;1.19 from central in [default]
	com.sun.jersey#jersey-json;1.19 from central in [default]
	com.sun.jersey#jersey-server;1.19 from central in [default]
	com.sun.jersey#jersey-servlet;1.19 from central in [default]
	com.sun.xml.bind#jaxb-impl;2.2.3-1 from central in [default]
	com.thoughtworks.paranamer#paranamer;2.3 from central in [default]
	commons-beanutils#commons-beanutils;1.9.3 from central in [default]
	commons-cli#commons-cli;1.2 from central in [default]
	commons-codec#commons-codec;1.11 from central in [default]
	commons-collections#commons-collections;3.2.2 from central in [default]
	commons-io#commons-io;2.5 from central in [default]
	commons-logging#commons-logging;1.1.3 from central in [default]
	commons-net#commons-net;3.6 from central in [default]
	dnsjava#dnsjava;2.1.7 from central in [default]
	io.netty#netty;3.10.5.Final from central in [default]
	javax.servlet#javax.servlet-api;3.1.0 from central in [default]
	javax.servlet.jsp#jsp-api;2.1 from central in [default]
	javax.ws.rs#jsr311-api;1.1.1 from central in [default]
	javax.xml.bind#jaxb-api;2.2.11 from central in [default]
	jline#jline;0.9.94 from central in [default]
	log4j#log4j;1.2.17 from central in [default]
	net.minidev#accessors-smart;1.2 from central in [default]
	net.minidev#json-smart;2.3 from central in [default]
	org.apache.avro#avro;1.7.7 from central in [default]
	org.apache.commons#commons-compress;1.4.1 from central in [default]
	org.apache.commons#commons-configuration2;2.1.1 from central in [default]
	org.apache.commons#commons-lang3;3.7 from central in [default]
	org.apache.commons#commons-math3;3.1.1 from central in [default]
	org.apache.commons#commons-text;1.4 from central in [default]
	org.apache.curator#curator-client;2.12.0 from central in [default]
	org.apache.curator#curator-framework;2.12.0 from central in [default]
	org.apache.curator#curator-recipes;2.12.0 from central in [default]
	org.apache.hadoop#hadoop-annotations;3.2.0 from central in [default]
	org.apache.hadoop#hadoop-auth;3.2.0 from central in [default]
	org.apache.hadoop#hadoop-aws;3.2.0 from central in [default]
	org.apache.hadoop#hadoop-common;3.2.0 from central in [default]
	org.apache.htrace#htrace-core4;4.1.0-incubating from central in [default]
	org.apache.httpcomponents#httpclient;4.5.2 from central in [default]
	org.apache.httpcomponents#httpcore;4.4.4 from central in [default]
	org.apache.kerby#kerb-admin;1.0.1 from central in [default]
	org.apache.kerby#kerb-client;1.0.1 from central in [default]
	org.apache.kerby#kerb-common;1.0.1 from central in [default]
	org.apache.kerby#kerb-core;1.0.1 from central in [default]
	org.apache.kerby#kerb-crypto;1.0.1 from central in [default]
	org.apache.kerby#kerb-identity;1.0.1 from central in [default]
	org.apache.kerby#kerb-server;1.0.1 from central in [default]
	org.apache.kerby#kerb-simplekdc;1.0.1 from central in [default]
	org.apache.kerby#kerb-util;1.0.1 from central in [default]
	org.apache.kerby#kerby-asn1;1.0.1 from central in [default]
	org.apache.kerby#kerby-config;1.0.1 from central in [default]
	org.apache.kerby#kerby-pkix;1.0.1 from central in [default]
	org.apache.kerby#kerby-util;1.0.1 from central in [default]
	org.apache.kerby#kerby-xdr;1.0.1 from central in [default]
	org.apache.kerby#token-provider;1.0.1 from central in [default]
	org.apache.yetus#audience-annotations;0.5.0 from central in [default]
	org.apache.zookeeper#zookeeper;3.4.13 from central in [default]
	org.codehaus.jackson#jackson-core-asl;1.9.13 from central in [default]
	org.codehaus.jackson#jackson-jaxrs;1.9.13 from central in [default]
	org.codehaus.jackson#jackson-mapper-asl;1.9.13 from central in [default]
	org.codehaus.jackson#jackson-xc;1.9.13 from central in [default]
	org.codehaus.jettison#jettison;1.1 from central in [default]
	org.codehaus.woodstox#stax2-api;3.1.4 from central in [default]
	org.eclipse.jetty#jetty-http;9.3.24.v20180605 from central in [default]
	org.eclipse.jetty#jetty-io;9.3.24.v20180605 from central in [default]
	org.eclipse.jetty#jetty-security;9.3.24.v20180605 from central in [default]
	org.eclipse.jetty#jetty-server;9.3.24.v20180605 from central in [default]
	org.eclipse.jetty#jetty-servlet;9.3.24.v20180605 from central in [default]
	org.eclipse.jetty#jetty-util;9.3.24.v20180605 from central in [default]
	org.eclipse.jetty#jetty-webapp;9.3.24.v20180605 from central in [default]
	org.eclipse.jetty#jetty-xml;9.3.24.v20180605 from central in [default]
	org.ow2.asm#asm;5.0.4 from central in [default]
	org.slf4j#slf4j-api;1.7.25 from central in [default]
	org.slf4j#slf4j-log4j12;1.7.25 from central in [default]
	org.tukaani#xz;1.0 from central in [default]
	org.xerial.snappy#snappy-java;1.0.5 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   88  |   0   |   0   |   0   ||   87  |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-08dd3632-27d9-4bd1-b0b7-02d2b0a97b9a
	confs: [default]
	0 artifacts copied, 87 already retrieved (0kB/38ms)
24/10/31 12:47:06 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).

## 1. Extract from object storage

In [2]:
os.environ['S3_INPUT_PATH'] = "s3a://velib/silver/velib-disponibilite-en-temps-reel"

spark.sparkContext.setLogLevel("WARN")

df = spark.read.parquet(os.getenv("S3_INPUT_PATH"))
df.printSchema()
print(f'COUNT = {df.count()}')
df.limit(10).toPandas()

24/10/31 12:47:12 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
24/10/31 12:47:19 WARN DataSource: Found duplicate column(s) in the data schema and the partition schema: `part_day`

root
 |-- capacity: long (nullable = true)
 |-- code_insee_commune: string (nullable = true)
 |-- duedate: string (nullable = true)
 |-- duedate_timestamp_minute: timestamp (nullable = true)
 |-- ebike: long (nullable = true)
 |-- fill_percentage: double (nullable = true)
 |-- fill_ratio: double (nullable = true)
 |-- is_installed: string (nullable = true)
 |-- is_renting: string (nullable = true)
 |-- is_returning: string (nullable = true)
 |-- lat: double (nullable = true)
 |-- lon: double (nullable = true)
 |-- mechanical: long (nullable = true)
 |-- name: string (nullable = true)
 |-- nom_arrondissement_communes: string (nullable = true)
 |-- numbikesavailable: long (nullable = true)
 |-- numdocksavailable: long (nullable = true)
 |-- part_day: date (nullable = true)
 |-- part_minute: string (nullable = true)
 |-- part_month: string (nullable = true)
 |-- polldate: string (nullable = true)
 |-- polldate_timestamp_minute: timestamp (nullable = true)
 |-- stationcode: string (nullable = true)

COUNT = 2759402

,capacity,code_insee_commune,duedate,duedate_timestamp_minute,ebike,fill_percentage,fill_ratio,is_installed,is_renting,is_returning,...,name,nom_arrondissement_communes,numbikesavailable,numdocksavailable,part_day,part_minute,part_month,polldate,polldate_timestamp_minute,stationcode
0,20,94081,2024-10-29T20:09:07+00:00,2024-10-29 20:09:00,7,75.0,0.750,OUI,OUI,OUI,...,Rouget de L'isle - Watteau,Vitry-sur-Seine,15,4,2024-10-29,2024-10-29T20:17,2024-10,2024-10-29T20:17:00+00:00,2024-10-29 20:17:00,44015
1,35,75056,2024-10-29T20:11:10+00:00,2024-10-29 20:11:00,0,8.6,0.086,OUI,OUI,OUI,...,Benjamin Godard - Victor Hugo,Paris,3,32,2024-10-29,2024-10-29T20:17,2024-10,2024-10-29T20:17:00+00:00,2024-10-29 20:17:00,16107
2,60,75056,2024-10-29T20:05:49+00:00,2024-10-29 20:05:00,5,20.0,0.200,OUI,OUI,OUI,...,Jourdan - Stade Charléty,Paris,12,48,2024-10-29,2024-10-29T20:17,2024-10,2024-10-29T20:17:00+00:00,2024-10-29 20:17:00,14014
3,21,75056,2024-10-29T20:08:35+00:00,2024-10-29 20:08:00,8,52.4,0.524,OUI,OUI,OUI,...,Toudouze - Clauzel,Paris,11,10,2024-10-29,2024-10-29T20:17,2024-10,2024-10-29T20:17:00+00:00,2024-10-29 20:17:00,9020
4,12,75056,2024-10-29T20:09:46+00:00,2024-10-29 20:09:00,0,8.3,0.083,OUI,OUI,OUI,...,Messine - Place Du Pérou,Paris,1,10,2024-10-29,2024-10-29T20:17,2024-10,2024-10-29T20:17:00+00:00,2024-10-29 20:17:00,8026
5,25,75056,2024-10-29T20:12:09+00:00,2024-10-29 20:12:00,3,16.0,0.160,OUI,OUI,OUI,...,Cassini - Denfert-Rochereau,Paris,4,17,2024-10-29,2024-10-29T20:17,2024-10,2024-10-29T20:17:00+00:00,2024-10-29 20:17:00,14111
6,48,75056,2024-10-29T20:10:21+00:00,2024-10-29 20:10:00,5,20.8,0.208,OUI,OUI,OUI,...,Le Brun - Gobelins,Paris,10,38,2024-10-29,2024-10-29T20:17,2024-10,2024-10-29T20:17:00+00:00,2024-10-29 20:17:00,13007
7,22,93066,2024-10-29T20:10:15+00:00,2024-10-29 20:10:00,6,59.1,0.591,OUI,OUI,OUI,...,Basilique,Saint-Denis,13,8,2024-10-29,2024-10-29T20:17,2024-10,2024-10-29T20:17:00+00:00,2024-10-29 20:17:00,32017
8,35,75056,2024-10-29T20:09:04+00:00,2024-10-29 20:09:00,2,68.6,0.686,OUI,OUI,OUI,...,Vaneau - Sèvres,Paris,24,10,2024-10-29,2024-10-29T20:17,2024-10,2024-10-29T20:17:00+00:00,2024-10-29 20:17:00,7002
9,20,75056,2024-10-29T20:09:35+00:00,2024-10-29 20:09:00,0,0.0,0.000,OUI,OUI,OUI,...,Charonne - Robert et Sonia Delaunay,Paris,0,20,2024-10-29,2024-10-29T20:17,2024-10,2024-10-29T20:17:00+00:00,2024-10-29 20:17:00,11104

## 2. Transform

In [9]:
import pyspark.sql.functions as F
from pyspark.sql.window import Window

df_dict = {}

def calc_turnover_rate(input_df):
    windowSpec  = Window.partitionBy("stationcode", "ten_minute_interval").orderBy("polldate_timestamp_minute")

    df_transformed = input_df#.dropDuplicates(["stationcode", "polldate_timestamp_minute"])
    df_transformed = (
        df_transformed
        .withColumn("ten_minute_interval", F.substring("polldate", 1, 15))
        .withColumn("numbikesavailable_abs_lag_diff",
            F.abs(F.col("numbikesavailable") - F.lag("numbikesavailable", 1).over(windowSpec)))
        )
    df_transformed = (
        df_transformed
        .groupBy("stationcode", "ten_minute_interval")
        .agg(
            F.sum(F.col("numbikesavailable_abs_lag_diff")).alias("turnover_rate_10min"),
            F.first(F.col("name")).alias("name"),
            F.first(F.col("capacity")).alias("capacity"),
            F.first(F.col("part_day")).alias("part_day"),
            F.first(F.col("polldate_timestamp_minute")).alias("polldate_timestamp_minute")
        )
        .filter(F.col("turnover_rate_10min") < 500)
        .na.fill({'turnover_rate_10min': .0})
    )
    df_transformed = df_transformed.select(*(sorted(df_transformed.columns)))
    return df_transformed

df_dict['turnover_rate_10min'] = calc_turnover_rate(df)
df_dict['turnover_rate_10min'].printSchema()
print(f"COUNT = {df_dict['turnover_rate_10min'].count()}")

import pandas as pd
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.width', 1000)
# df_dict['turnover_rate_10min'].orderBy("ten_minute_interval", ascending=True).limit(10).toPandas()
# df_dict['turnover_rate_10min'].select("turnover_rate_10min").distinct().orderBy("turnover_rate_10min", ascending=False).limit(100).toPandas()
df_dict['turnover_rate_10min'].limit(10).toPandas()
# df_dict['turnover_rate_10min'].summary().show()

root
 |-- capacity: long (nullable = true)
 |-- name: string (nullable = true)
 |-- part_day: date (nullable = true)
 |-- polldate_timestamp_minute: timestamp (nullable = true)
 |-- stationcode: string (nullable = true)
 |-- ten_minute_interval: string (nullable = true)
 |-- turnover_rate_10min: long (nullable = true)

COUNT = 301599

   capacity                                     name    part_day polldate_timestamp_minute stationcode ten_minute_interval  turnover_rate_10min
0        17              Hauteville - Bonne Nouvelle  2024-10-30       2024-10-30 19:10:00       10003     2024-10-30T19:1                    7
1        17              Hauteville - Bonne Nouvelle  2024-10-31       2024-10-31 02:20:00       10003     2024-10-31T02:2                    2
2        48              Metz - Faubourg Saint-Denis  2024-10-29       2024-10-29 21:20:00       10004     2024-10-29T21:2                    4
3        48              Metz - Faubourg Saint-Denis  2024-10-29       2024-10-29 22:50:00       10004     2024-10-29T22:5                    5
4        17  Petites Ecuries - Faubourg Poissonnière  2024-10-31       2024-10-31 10:50:00       10005     2024-10-31T10:5                    0
5        28   Petites Ecuries - Faubourg Saint-Denis  2024-10-30       2024-10-30 22:20:00       10006     2024-10-30T22:2                    5
6        18             Cité Riverin - Château d'Eau  2024-10-30       2024-10-30 02:10:00       10008     2024-10-30T02:1                    0
7        18             Cité Riverin - Château d'Eau  2024-10-31       2024-10-31 01:10:00       10008     2024-10-31T01:1                    3
8        17            Quai de l'Horloge - Pont Neuf  2024-10-30       2024-10-30 11:20:00        1001     2024-10-30T11:2                    0
9        17            Quai de l'Horloge - Pont Neuf  2024-10-31       2024-10-31 12:20:00        1001     2024-10-31T12:2                    0

## 3. Load into object storage

In [10]:
os.environ['S3_OUTPUT_PATH'] = "s3a://velib/gold/turnover-rate-by-station-10min"

spark.sparkContext.setLogLevel("WARN")

# Write DataFrame to S3
(
    df_transformed.write
    .partitionBy("part_day")
    .format("parquet")
    .mode("overwrite")
    .save(os.getenv('S3_OUTPUT_PATH'))
)

## 4. Update hive metastore

In [11]:
!pip install trino

Requirement already satisfied: trino in /opt/conda/lib/python3.9/site-packages (0.330.0)
Requirement already satisfied: requests>=2.31.0 in /opt/conda/lib/python3.9/site-packages (from trino) (2.32.3)
Requirement already satisfied: tzlocal in /opt/conda/lib/python3.9/site-packages (from trino) (5.2)
Requirement already satisfied: python-dateutil in /opt/conda/lib/python3.9/site-packages (from trino) (2.8.2)
Requirement already satisfied: pytz in /opt/conda/lib/python3.9/site-packages (from trino) (2021.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.9/site-packages (from requests>=2.31.0->trino) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.9/site-packages (from requests>=2.31.0->trino) (3.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.9/site-packages (from requests>=2.31.0->trino) (1.26.7)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.9/site-packages (from requests>=2.31.0->trino) (2.0.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.9/site-packages (from python-dateutil->trino) (1.16.0)

In [12]:
from pyspark.sql import DataFrame

def generate_trino_create_table(
    df: DataFrame, 
    catalog: str, 
    schema: str, 
    table: str, 
    partitioned_by: str, 
    external_location: str
) -> str:
    # Comprehensive mapping of Spark SQL types to Trino types
    type_mapping = {
        "bigint": "BIGINT",
        "binary": "VARBINARY",
        "boolean": "BOOLEAN",
        "decimal": "DECIMAL",  # Precision and scale will need to be handled separately if defined
        "double": "DOUBLE",
        "float": "REAL",
        "int": "INTEGER",
        "smallint": "SMALLINT",
        "string": "VARCHAR",
        "timestamp": "TIMESTAMP",
        "tinyint": "TINYINT"
    }
    
    # Separate columns to ensure partition column is placed last
    columns = []
    partition_column = None
    for field in df.schema.fields:
        spark_type = field.dataType.simpleString()
        trino_type = type_mapping.get(spark_type, "VARCHAR")  # default to VARCHAR if no match
        # DEBUG # print(f'field.name={field.name}, spark_type={spark_type}, trino_type={trino_type}')
        if field.name == partitioned_by:
            partition_column = f"{field.name} {trino_type}"
        else:
            columns.append(f"{field.name} {trino_type}")
    
    # Add the partition column to the end if it exists in the schema
    if partition_column:
        columns.append(partition_column)
    
    # Join column definitions into a single string
    columns_definition = ",\n    ".join(columns)
    
    # Generate the final CREATE TABLE statement
    create_table_sql = f"""
    CREATE TABLE IF NOT EXISTS {catalog}.{schema}.{table} (
        {columns_definition}
    ) 
    WITH (
        format = 'PARQUET',
        partitioned_by = ARRAY['{partitioned_by}'],
        external_location = '{external_location}'
    )
    """
    
    return create_table_sql.strip()

In [13]:
import trino

host, port, user = 'trino-coordinator', 8080, 'trino'
conn = trino.dbapi.connect(host=host, port=port, user=user)
cur = conn.cursor()

catalog, schema, table = 'minio', 'velib_gold', 'turnover_rate_by_station_10min'
schema_location = 's3a://velib/gold/'
partitioned_by = 'part_day'
external_location = 's3a://velib/gold/turnover-rate-by-station-10min'

# List of queries to execute
queries = [
    f"CREATE SCHEMA IF NOT EXISTS {catalog}.{schema} WITH (location = '{schema_location}')",
    f"DROP TABLE IF EXISTS {catalog}.{schema}.{table}",
    
    generate_trino_create_table(df_transformed, catalog, schema, table, partitioned_by, external_location),
    
    f"USE {catalog}.{schema}",
    f"CALL system.sync_partition_metadata('{schema}', '{table}', 'ADD')",
    f"SELECT * FROM {catalog}.{schema}.{table} LIMIT 10"
]

# Execute each query in the list
for query in queries:
    try:
        cur.execute(query)
        # Check if the query is a SELECT query to fetch results
        if query.startswith("SELECT"):
            results = cur.fetchall()
            for row in results:
                print(row)
        else:
            print(f"Executed: {query}")
    except Exception as e:
        print(f"Error executing query: {query}. Error: {e}")

# Close the cursor and connection
cur.close()
conn.close()

Executed: CREATE SCHEMA IF NOT EXISTS minio.velib_gold WITH (location = 's3a://velib/gold/')
Executed: DROP TABLE IF EXISTS minio.velib_gold.turnover_rate_by_station_10min
Executed: CREATE TABLE IF NOT EXISTS minio.velib_gold.turnover_rate_by_station_10min (
        capacity BIGINT,
    code_insee_commune VARCHAR,
    duedate VARCHAR,
    duedate_timestamp_minute TIMESTAMP,
    ebike BIGINT,
    fill_percentage DOUBLE,
    fill_ratio DOUBLE,
    is_installed VARCHAR,
    is_renting VARCHAR,
    is_returning VARCHAR,
    lat DOUBLE,
    lon DOUBLE,
    mechanical BIGINT,
    name VARCHAR,
    nom_arrondissement_communes VARCHAR,
    numbikesavailable BIGINT,
    numdocksavailable BIGINT,
    part_minute VARCHAR,
    part_month VARCHAR,
    polldate VARCHAR,
    polldate_timestamp_minute TIMESTAMP,
    stationcode VARCHAR,
    part_day VARCHAR
    )
    WITH (
        format = 'PARQUET',
        partitioned_by = ARRAY['part_day'],
        external_location = 's3a://velib/gold/turnover-rate-by-station-10min'
    )
Executed: USE minio.velib_gold
Executed: CALL system.sync_partition_metadata('velib_gold', 'turnover_rate_by_station_10min', 'ADD')
[29, '75056', '2024-10-31T01:14:53+00:00', datetime.datetime(2024, 10, 31, 1, 14), 12, 51.7, 0.517, 'OUI', 'OUI', 'OUI', 48.83453413883994, 2.313154547426182, 3, 'Gergovie - Vercingétorix', 'Paris', 15, 13, '2024-10-31T02:15', '2024-10', '2024-10-31T02:15:00+00:00', datetime.datetime(2024, 10, 31, 2, 15), '14128', '2024-10-31']
[35, '75056', '2024-10-30T02:03:24+00:00', datetime.datetime(2024, 10, 30, 2, 3), 1, 11.4, 0.114, 'OUI', 'OUI', 'OUI', 48.865983, 2.275725, 3, 'Benjamin Godard - Victor Hugo', 'Paris', 4, 31, '2024-10-30T02:29', '2024-10', '2024-10-30T02:29:00+00:00', datetime.datetime(2024, 10, 30, 2, 29), '16107', '2024-10-30']
[20, '94081', '2024-10-30T02:10:00+00:00', datetime.datetime(2024, 10, 30, 2, 10), 12, 95.0, 0.95, 'OUI', 'OUI', 'OUI', 48.778192750803, 2.3963020229163, 7, "Rouget de L'isle - Watteau", 'Vitry-sur-Seine', 19, 0, '2024-10-30T02:29', '2024-10', '2024-10-30T02:29:00+00:00', datetime.datetime(2024, 10, 30, 2, 29), '44015', '2024-10-30']
[25, '75056', '2024-10-30T02:12:47+00:00', datetime.datetime(2024, 10, 30, 2, 12), 2, 12.0, 0.12, 'OUI', 'OUI', 'OUI', 48.837525839067, 2.3360354080796, 1, 'Cassini - Denfert-Rochereau', 'Paris', 3, 18, '2024-10-30T02:29', '2024-10', '2024-10-30T02:29:00+00:00', datetime.datetime(2024, 10, 30, 2, 29), '14111', '2024-10-30']
[21, '75056', '2024-10-30T02:09:03+00:00', datetime.datetime(2024, 10, 30, 2, 9), 1, 19.0, 0.19, 'OUI', 'OUI', 'OUI', 48.87929591733507, 2.3373600840568547, 3, 'Toudouze - Clauzel', 'Paris', 4, 14, '2024-10-30T02:29', '2024-10', '2024-10-30T02:29:00+00:00', datetime.datetime(2024, 10, 30, 2, 29), '9020', '2024-10-30']
[22, '93066', '2024-10-30T02:12:54+00:00', datetime.datetime(2024, 10, 30, 2, 12), 7, 54.50000000000001, 0.545, 'OUI', 'OUI', 'OUI', 48.93626891059109, 2.3588666820200914, 5, 'Basilique', 'Saint-Denis', 12, 9, '2024-10-30T02:29', '2024-10', '2024-10-30T02:29:00+00:00', datetime.datetime(2024, 10, 30, 2, 29), '32017', '2024-10-30']
[60, '75056', '2024-10-30T02:08:25+00:00', datetime.datetime(2024, 10, 30, 2, 8), 9, 30.0, 0.3, 'OUI', 'OUI', 'OUI', 48.819428333369, 2.3433353751898, 9, 'Jourdan - Stade Charléty', 'Paris', 18, 42, '2024-10-30T02:29', '2024-10', '2024-10-30T02:29:00+00:00', datetime.datetime(2024, 10, 30, 2, 29), '14014', '2024-10-30']
[20, '75056', '2024-10-30T02:12:10+00:00', datetime.datetime(2024, 10, 30, 2, 12), 1, 50.0, 0.5, 'OUI', 'OUI', 'OUI', 48.855907555969, 2.3925706744194, 9, 'Charonne - Robert et Sonia Delaunay', 'Paris', 10, 10, '2024-10-30T02:29', '2024-10', '2024-10-30T02:29:00+00:00', datetime.datetime(2024, 10, 30, 2, 29), '11104', '2024-10-30']
[12, '75056', '2024-10-30T02:10:13+00:00', datetime.datetime(2024, 10, 30, 2, 10), 1, 33.300000000000004, 0.333, 'OUI', 'OUI', 'OUI', 48.875448033960744, 2.315508019010038, 3, 'Messine - Place Du Pérou', 'Paris', 4, 7, '2024-10-30T02:29', '2024-10', '2024-10-30T02:29:00+00:00', datetime.datetime(2024, 10, 30, 2, 29), '8026', '2024-10-30']
[48, '75056', '2024-10-30T02:11:02+00:00', datetime.datetime(2024, 10, 30, 2, 11), 3, 14.6, 0.146, 'OUI', 'OUI', 'OUI', 48.835092787824, 2.3534681351338, 4, 'Le Brun - Gobelins', 'Paris', 7, 39, '2024-10-30T02:29', '2024-10', '2024-10-30T02:29:00+00:00', datetime.datetime(2024, 10, 30, 2, 29), '13007', '2024-10-30']